import styles from './main.module.scss';

export const MainPage = () => {
    return(
        <div>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>
            <p>sdgsdfv</p><br/>

        </div>
    )
}